server:
  port: 8088
# 拦截
  servlet:
    path: /
logging:
  level:
    cn.itcast: debug
    # org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.pojo
  # mapper-locations: mapper/*.xml